/**
 * Author:  Coffeeddicted
 * Created: 14 mars 2018
 *
 * Preload data for unit tests.
 * Designed for H2 in-memory (AutoConfigured thanks to Spring Boot).
 */

/*
 * Class SomethingType
 * Table SOMETHING_TYPE [ ID , NAME ]
 */
SELECT SEQ_SOMETHING_TYPE.nextval FROM DUAL;
INSERT INTO SOMETHING_TYPE VALUES (SEQ_SOMETHING_TYPE.currval, 'Some type'); -- 1
SELECT SEQ_SOMETHING_TYPE.nextval FROM DUAL;
INSERT INTO SOMETHING_TYPE VALUES (SEQ_SOMETHING_TYPE.currval, 'Some other type'); -- 2
SELECT SEQ_SOMETHING_TYPE.nextval FROM DUAL;
INSERT INTO SOMETHING_TYPE VALUES (SEQ_SOMETHING_TYPE.currval, 'Some type again'); -- 3
SELECT SEQ_SOMETHING_TYPE.nextval FROM DUAL;
INSERT INTO SOMETHING_TYPE VALUES (SEQ_SOMETHING_TYPE.currval, 'Some other type again'); -- 4
SELECT SEQ_SOMETHING_TYPE.nextval FROM DUAL;
INSERT INTO SOMETHING_TYPE VALUES (SEQ_SOMETHING_TYPE.currval, 'Some type again'); -- 5

/*
 * Class Something
 * Table SOMETHING [ ID , NAME, PRIMARY_SOMETHING_TYPE, SECONDARY_SOMETHING_TYPE ]
 */
SELECT SEQ_SOMETHING.nextval FROM DUAL;
INSERT INTO SOMETHING VALUES (SEQ_SOMETHING.currval, 'Something 1', 1, 2); -- 1
SELECT SEQ_SOMETHING.nextval FROM DUAL;
INSERT INTO SOMETHING VALUES (SEQ_SOMETHING.currval, 'Something 2', 1, NULL); -- 2
SELECT SEQ_SOMETHING.nextval FROM DUAL;
INSERT INTO SOMETHING VALUES (SEQ_SOMETHING.currval, 'Something 3', 3, 1); -- 3
SELECT SEQ_SOMETHING.nextval FROM DUAL;
INSERT INTO SOMETHING VALUES (SEQ_SOMETHING.currval, 'Something 4', 1, 3); -- 4
SELECT SEQ_SOMETHING.nextval FROM DUAL;
INSERT INTO SOMETHING VALUES (SEQ_SOMETHING.currval, 'Something 5', 1, NULL); -- 5
SELECT SEQ_SOMETHING.nextval FROM DUAL;
INSERT INTO SOMETHING VALUES (SEQ_SOMETHING.currval, 'Something 6', 2, 2); -- 6
SELECT SEQ_SOMETHING.nextval FROM DUAL;
INSERT INTO SOMETHING VALUES (SEQ_SOMETHING.currval, 'Something 7', 4, 1); -- 7
SELECT SEQ_SOMETHING.nextval FROM DUAL;
INSERT INTO SOMETHING VALUES (SEQ_SOMETHING.currval, 'Something 8', 4, 1); -- 8
SELECT SEQ_SOMETHING.nextval FROM DUAL;
INSERT INTO SOMETHING VALUES (SEQ_SOMETHING.currval, 'Something 9', 4, 3); -- 9
SELECT SEQ_SOMETHING.nextval FROM DUAL;
INSERT INTO SOMETHING VALUES (SEQ_SOMETHING.currval, 'Something 10', 4, 2); -- 10
